import { NextRequest, NextResponse } from 'next/server'
import { createServiceClient } from '@/lib/supabase/service'
import { getNgoSession, requireRole } from '@/lib/ngo-auth'
import type { GatheredData } from '@/lib/ngo-reports'

// GET /api/ngo/reports/[id]/export?format=doc
// Renders a saved report as a styled HTML document served as application/msword —
// Word and Google Docs open it natively, no PDF/Word library needed. org-scoped.

function esc(s: unknown): string {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

export async function GET(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const session = await getNgoSession(request)
  if (!requireRole(session, ['org_admin', 'team_leader'])) {
    return NextResponse.json({ error: 'Not authorised' }, { status: 403 })
  }
  const { id } = await params
  const supabase = createServiceClient()
  const { data: report, error } = await supabase
    .from('ngo_reports')
    .select('title, period_start, period_end, created_at, draft, data')
    .eq('id', id)
    .eq('org_id', session!.orgId)
    .maybeSingle()
  if (error) return NextResponse.json({ error: 'Could not load report' }, { status: 500 })
  if (!report) return NextResponse.json({ error: 'Report not found' }, { status: 404 })

  const data = (report.data ?? {}) as Partial<GatheredData>
  const fig = data.figures
  const period = `${String(report.period_start).slice(0, 10)} → ${String(report.period_end).slice(0, 10)}`

  // Draft narrative: preserve line breaks; if absent, note it.
  const draftHtml = report.draft
    ? esc(report.draft).replace(/\n{2,}/g, '</p><p>').replace(/\n/g, '<br/>')
    : '<em>No AI narrative was generated for this report. The underlying data is included below.</em>'

  const incidentRows = (data.incidents ?? [])
    .map(
      (i) =>
        `<tr><td>${esc(i.location_name ?? '—')}</td><td>${esc((i.event_types ?? []).join(', '))}</td>` +
        `<td>${esc(i.source)}</td><td>${esc(i.confidence_score ?? '—')}</td><td>${esc(String(i.created_at).slice(0, 16).replace('T', ' '))}</td></tr>`,
    )
    .join('')

  const dispatchRows = (data.dispatches ?? [])
    .map(
      (d) =>
        `<tr><td>${esc(d.team_name ?? '—')}${d.team_type ? ` (${esc(d.team_type)})` : ''}</td><td>${esc(d.status)}</td>` +
        `<td>${esc(d.people_assisted ?? '—')}</td><td>${esc(d.services ?? '—')}</td><td>${esc(d.new_hazards ?? '—')}</td></tr>`,
    )
    .join('')

  const figuresHtml = fig
    ? `<ul>
        <li>Verified incidents in area: <strong>${esc(fig.incident_count)}</strong></li>
        <li>Dispatches: <strong>${esc(fig.dispatch_count)}</strong> (${esc(
          Object.entries(fig.dispatches_by_status).map(([k, v]) => `${k}: ${v}`).join(', ') || 'none',
        )})</li>
        <li>People assisted: <strong>${esc(fig.total_people_assisted)}</strong></li>
        <li>New hazards reported: <strong>${esc(fig.new_hazards_reported)}</strong></li>
       </ul>`
    : '<p>No figures available.</p>'

  const html = `<!doctype html>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
<head><meta charset="utf-8"/><title>${esc(report.title)}</title>
<style>
  body { font-family: Calibri, Arial, sans-serif; color: #111; font-size: 11pt; }
  h1 { font-size: 18pt; margin: 0 0 4pt; }
  h2 { font-size: 13pt; border-bottom: 1px solid #999; padding-bottom: 2pt; margin-top: 18pt; }
  .meta { color: #555; font-size: 9pt; margin-bottom: 12pt; }
  table { border-collapse: collapse; width: 100%; font-size: 9pt; margin-top: 6pt; }
  th, td { border: 1px solid #bbb; padding: 4pt 6pt; text-align: left; vertical-align: top; }
  th { background: #eee; }
  .footnote { color: #777; font-size: 8pt; margin-top: 20pt; }
</style></head>
<body>
  <h1>${esc(report.title)}</h1>
  <div class="meta">Reporting period: ${esc(period)} &nbsp;·&nbsp; Generated: ${esc(String(report.created_at).slice(0, 16).replace('T', ' '))} UTC</div>
  <div><p>${draftHtml}</p></div>
  <h2>Key figures</h2>
  ${figuresHtml}
  <h2>Verified incidents in operational area (${esc((data.incidents ?? []).length)})</h2>
  ${incidentRows ? `<table><tr><th>Location</th><th>Type</th><th>Source</th><th>Confidence</th><th>Time (UTC)</th></tr>${incidentRows}</table>` : '<p>None in this period.</p>'}
  <h2>Dispatches &amp; on-scene reports (${esc((data.dispatches ?? []).length)})</h2>
  ${dispatchRows ? `<table><tr><th>Team</th><th>Status</th><th>People assisted</th><th>Services</th><th>New hazards</th></tr>${dispatchRows}</table>` : '<p>None in this period.</p>'}
  <div class="footnote">Generated by NOUR from verified incident records and the organisation's own dispatch data. Figures reflect only records held in the system for the stated period.</div>
</body></html>`

  const dateStr = new Date().toISOString().slice(0, 10)
  const safeTitle = String(report.title).replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '').slice(0, 40) || 'sitrep'
  return new NextResponse(html, {
    headers: {
      'Content-Type': 'application/msword',
      'Content-Disposition': `attachment; filename="${safeTitle}-${dateStr}.doc"`,
      'Cache-Control': 'no-store',
    },
  })
}
