-- ============================================================
-- NGO saved situation reports (additive, new table only)
-- ============================================================
-- Stores OCHA-style sitreps generated by an org from its incidents, dispatches,
-- and on-scene reports for a date range. Separate from the civilian/admin
-- `situation_reports` table — this is org-scoped NGO data. No existing table is
-- altered. Service-role only (RLS enabled, no public policy); the API enforces
-- org-scope via .eq('org_id', session.orgId), matching every other ngo_* table.
-- ============================================================

create table if not exists ngo_reports (
  id            uuid        primary key default gen_random_uuid(),
  org_id        uuid        not null references ngo_organisations (id) on delete cascade,
  title         text        not null,
  period_start  timestamptz not null,
  period_end    timestamptz not null,
  draft         text,                                  -- AI-generated sitrep narrative (null if AI unavailable)
  data          jsonb,                                 -- snapshot of the gathered records + key figures
  generated_by  uuid        references ngo_users (id) on delete set null,
  created_at    timestamptz not null default now()
);
create index if not exists ngo_reports_org_id on ngo_reports (org_id);
create index if not exists ngo_reports_created_at on ngo_reports (org_id, created_at desc);

alter table ngo_reports enable row level security;
